external_data_config:
  external_dataset: C:/Users/thuan/Desktop/CVCI/Final_project/final_cvci/data\external/classification-of-plants-of-southeast-asia/bali-26_train/bali-26_train


mlflow_config:  
  artifacts_dir: artifacts
  experiment_name: model_image_classifier
  run_name: mobileNet
  registered_model_name: mobileNet_model
  remote_server_uri: http://localhost:5000

mobileNet:
  epochs: 1

model_dir: C:/Users/thuan/Desktop/CVCI/Final_project/final_cvci/src/models/model.pth