external_data_config:
  external_dataset: data/external/classification-of-plants-of-southeast-asia/bali-26_train/bali-26_train


mlflow_config:  
  artifacts_dir: artifacts
  experiment_name: model_image_classifier
  run_name: mobileNet
  registered_model_name: mobileNet_model
  remote_server_uri: http://localhost:5000

mobileNet:
  epochs: 1

model_dir: models/model.pth