channels:
- conda-forge
dependencies:
- python=3.7.13
- pip<=21.2.4
- pip:
  - mlflow
  - cffi==1.15.0
  - cloudpickle==2.1.0
  - ipython==7.33.0
  - torch==1.11.0
  - torchvision==0.12.0
  - tqdm==4.64.0
name: mlflow-env
